dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
os:
  - osx
  - linux
addons:
  apt:
    packages:
    - rpm
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS" LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"; fi'
install:
  - npm install
script:
  - npm test
deploy:
  provider: script
  skip_cleanup: true
  script: electron-forge publish
  on:
    branch:
      - master
